# Generated by Django 3.2.18 on 2023-06-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Application name')),
                ('description', models.CharField(max_length=300, verbose_name='Application description')),
                ('url', models.URLField(verbose_name='URL of application location')),
            ],
        ),
    ]
